### ISSUE TITLE
你节衣缩食抢一张千元演唱会门票的样子，周杰伦看了都会心疼丨腾讯新闻谷雨数据

### ISSUE THREAD

**Issue by ixxmu** [ixxmu/hugo_duty#219]
https://mp.weixin.qq.com/s/PtD9sRgiyxvcjj_vmeM6vA

**Comment by ixxmu** [comment]
你节衣缩食抢一张千元演唱会门票的样子，周杰伦看了都会心疼丨腾讯新闻谷雨数据 by 谷雨数据-腾讯新闻
------
<div><p><img data-backh="297" data-backw="562" data-cropselx1="0" data-cropselx2="562" data-cropsely1="0" data-cropsely2="297" data-ratio="0.5278058645096056" data-src="https://mmbiz.qpic.cn/sz_mmbiz_jpg/HYpq6iceJNftpp5MmLAyqT5xB5J53LhQaj6T6e7GI0cpY5ic6zM1lzKPjSCYf7XE3LAibV3D6XyJNycjA4oeUOS2Q/640?wx_fmt=jpeg" data-type="jpeg" data-w="989" src="https://mmbiz.qpic.cn/sz_mmbiz_jpg/HYpq6iceJNftpp5MmLAyqT5xB5J53LhQaj6T6e7GI0cpY5ic6zM1lzKPjSCYf7XE3LAibV3D6XyJNycjA4oeUOS2Q/640?wx_fmt=jpeg"></p><section><strong><span>最热话题+最新数据</span></strong><span>，值得你<span>第一时间获取</span>，大家记得将</span><span><strong><span>谷雨数据</span></strong></span><span>设为星标🌟哦，期待每次与你火速相遇！</span></section><p><span data-font-family="default"><br></span></p><p><span>憋了三年的演唱会瘾，今年终于集中释放了。</span></p><p><p></p></p><p><span>每逢抢票和正式演出的日子，朋友圈总会轮番变成“五月天圈”“周杰伦圈”“BlackPink圈”。幸福的人在内场哼唱，线上围观的朋友跃跃欲试。</span><p></p></p><p><span><br></span></p><p><span>根据《证券日报》统计，截至5月，全国已举办近500场演唱会，超过2019年同期水平。</span><p></p></p><p><span><br></span></p><p><span>演出市场虽火，但吐槽的声音也不少。“抢票难”“黄牛猖獗”依然是高频词。为了一圆追星梦，咬牙加价花1000元坐场馆“山顶”的人不在少数。</span><p></p></p><p><span><br></span></p><p><span>人们不禁感叹：今年想看场心仪的演出，真难，真贵。</span><p></p></p><p><span><br></span></p><p><br></p><section><h4><section><section data-tools="135编辑器" data-id="93821"><section><section><section><span>01</span></section></section></section></section><section><br></section></section></h4><h4><strong><span><strong><span>欠自己的一场演唱会，</span></strong></span></strong></h4><h4><strong><span><strong><span>今年人人都在补</span></strong></span></strong></h4></section><p><span>临时买票，周末往返，看了BlackPink的曼谷演唱会，黄阳做了今年上半年最肆意的一个决定。但她觉得非常值。</span><p></p></p><p><span><br></span></p><p><span>“那种全场一起跟着唱跳的感觉，想起来都让我热泪盈眶。已经很久没有这么好的感觉了。”</span><p></p></p><p><span><br></span></p><p><span>现场演出让人上瘾。黄阳还研究起了薛之谦的票务来，她想和朋友找一些一直想去的巡演城市，将欠自己的旅游活动挨个补回来。</span><p></p></p><p><span><br></span></p><p><span>像黄阳一样，多地看演出顺带旅游的年轻“特种兵”不在少数。社交媒体平台上，分享演唱会抢票、订房、周边旅游推荐的攻略笔记越来越多。</span><p></p></p><p><span><br></span></p><p><span>根据中国演出行业协会《2023上半年全国演出市场简报》，2023年上半年，全国营业性演出（不含娱乐场所演出）观众人数达到6223.66万人次，较去年同比增长超10倍。演出场次19.33万场，与去年同比增长400.86%。</span><p></p></p><p><span><br></span></p><p><img data-backh="900" data-backw="578" data-galleryid="" data-ratio="1.5574074074074074" data-s="300,640" data-src="https://mmbiz.qpic.cn/sz_mmbiz_png/HYpq6iceJNftpp5MmLAyqT5xB5J53LhQaia5QBHicafVx0tsyy9pLVvJFgqvlZsIFO8sYiadAwsY7ia2UVfPLofhJ2g/640?wx_fmt=png" data-type="png" data-w="1080" src="https://mmbiz.qpic.cn/sz_mmbiz_png/HYpq6iceJNftpp5MmLAyqT5xB5J53LhQaia5QBHicafVx0tsyy9pLVvJFgqvlZsIFO8sYiadAwsY7ia2UVfPLofhJ2g/640?wx_fmt=png"></p><p><br></p><p><span>行业协会预计，进入暑期，线下演出市场持续升温。仅7月至8月，全国将有数百场演唱会、音乐节举行。</span><p></p></p><p><span><br></span></p><p><span>谷雨数据从大麦网上，收集了从年中到年尾已官宣的演唱会活动，共计1575场。在这里，“演唱会”包括了个人演唱会，拼盘演唱会与音乐节三种形式。一般来说，这些演出活动集中在未来1-2月，即8-9月，但也不乏早早开票，从10月贯穿到年底的系列巡演。</span><p></p></p><p><span><br></span></p><p><span>来看看今年演唱会的火热情况。从四大经济分区来看，东部地区不出意外占据了最多比重，其次是以成都、西安为代表的西部地区，和武汉、长沙为代表的中部地区，东北殿后。</span><p></p></p><p><span><br></span></p><p><span>具体到城市排名，上海凭借近期官宣的177场演唱会活动，遥遥领先。比位列第二的106场演唱会的北京，多出半个身位。广州、成都，紧随其后。</span><p></p></p><p><span><br></span></p><p><img data-backh="912" data-backw="562" data-cropselx1="0" data-cropselx2="562" data-cropsely1="0" data-cropsely2="911" data-galleryid="" data-ratio="1.6222222222222222" data-s="300,640" data-src="https://mmbiz.qpic.cn/sz_mmbiz_jpg/HYpq6iceJNfvicWAXLIZYDOUcndHz2NyUM5z5ricK5ew5f3ebWbcmkxm1icIZMJGibZETjP7pncBUTkDvWgQsvZ0IkA/640?wx_fmt=jpeg" data-type="png" data-w="1080" src="https://mmbiz.qpic.cn/sz_mmbiz_jpg/HYpq6iceJNfvicWAXLIZYDOUcndHz2NyUM5z5ricK5ew5f3ebWbcmkxm1icIZMJGibZETjP7pncBUTkDvWgQsvZ0IkA/640?wx_fmt=jpeg"></p><p><br></p><p><span>一线城市的演出活动多，并不稀奇。值得一提的是，以青岛、济南领衔的山东各地级市，凭借数量不少的演唱会活动，占据一席之地。</span><p></p></p><p><span><br></span></p><p><span>演唱会在淄博、菏泽、东营等次级城市遍地开花，这在其他省份少见。外地人少有人知的是，山东人很爱演唱会。其中，以摇滚、说唱、沙滩、电音为关键词的音乐节广受欢迎。</span><p></p></p><p><span><br></span></p><p><span>销量越好，场次就越多。金沙滩音乐节、新青年音乐节等本地原创的音乐品牌借此发展壮大，成为山东文旅的一张名片。</span><p></p></p><p><span><br></span></p><p><img data-backh="876" data-backw="578" data-galleryid="" data-ratio="1.5166666666666666" data-s="300,640" data-src="https://mmbiz.qpic.cn/sz_mmbiz_png/HYpq6iceJNftpp5MmLAyqT5xB5J53LhQawBlqjARGSlM6LOR7VxEI6okMtgHfFwj5U0AiahOrxXZia98NQfo9XL6A/640?wx_fmt=png" data-type="png" data-w="1080" src="https://mmbiz.qpic.cn/sz_mmbiz_png/HYpq6iceJNftpp5MmLAyqT5xB5J53LhQawBlqjARGSlM6LOR7VxEI6okMtgHfFwj5U0AiahOrxXZia98NQfo9XL6A/640?wx_fmt=png"></p><p><br></p><p><span>琳琅满目的演唱会中，哪些艺人演出最多，赚钱最忙？我们的数据显示，个人演唱会中，知名饶舌歌手Jony J凭借20场巡演居首。统一的400元票价，目前已全部售罄。</span><p></p></p><p><span><br></span></p><p><span>老牌歌手官宣的个人演唱会不少。其中，张韶涵，张信哲分别官宣11场和10场，位居前列。与Jony J在Livehouse的演出场地不同，这类歌手通常在大型体育场馆举办，容纳观众上万，单场票房也更高。而他们的销售情况同样良好，仅有个别高价套票剩余。</span><p></p></p><p><span><br></span></p><p><span>拼盘演出活动中，王以太、丢火车乐队、二手玫瑰、房东的猫等艺人最繁忙，已官宣的演出活动已有10场上下。</span></p><p><br></p><p><img data-backh="1016" data-backw="578" data-galleryid="" data-ratio="1.7583333333333333" data-s="300,640" data-src="https://mmbiz.qpic.cn/sz_mmbiz_png/HYpq6iceJNftpp5MmLAyqT5xB5J53LhQadRIyibUv6iaLdqRliaMOl6hmApybsp7uSQibh7T0zGiblD7AfiaA1iaq4Tn3Q/640?wx_fmt=png" data-type="png" data-w="1080" src="https://mmbiz.qpic.cn/sz_mmbiz_png/HYpq6iceJNftpp5MmLAyqT5xB5J53LhQadRIyibUv6iaLdqRliaMOl6hmApybsp7uSQibh7T0zGiblD7AfiaA1iaq4Tn3Q/640?wx_fmt=png"></p><p><span><br></span></p><p><br></p><section><h4><section><section data-tools="135编辑器" data-id="93821"><section><section><section><span>02</span></section></section></section></section><section><br></section></section></h4><h4><strong><span><strong><span>高票价也一座难求，</span></strong></span></strong></h4><h4><strong><span><strong><span>黄牛加价大行其道</span></strong></span></strong></h4></section><p><span>但不得不说的是，不论是音乐节还是个人演唱会，票价都越来越贵。</span></p><p><span></span><span></span></p><p><span><span>今年官宣的音乐节单日票价上涨至500元上下。</span><span>而疫情前的2019年，知名的草莓音乐节不过260元单日，学生票甚至可以低至200元。</span></span></p><p><span></span><br></p><p><span>这其中，有艺人报价的因素，也有物料、设备、场地租金等成本上涨的影响。谷雨数据整理了近期官宣的演唱会活动中，票档价位最高的前20场。其中，8月4日在张家口举办的2023虾米xMTA天漠音乐节以16800元的最高价格位居第一。</span><p></p></p><p><span><br></span></p><p><img data-backh="1247" data-backw="578" data-galleryid="" data-ratio="2.1574074074074074" data-s="300,640" data-src="https://mmbiz.qpic.cn/sz_mmbiz_png/HYpq6iceJNftpp5MmLAyqT5xB5J53LhQaKlaDweujWs4dH3IbSmmCqSrOmX87IpVsx76jcFUsC7r624FS4HDia9w/640?wx_fmt=png" data-type="png" data-w="1080" src="https://mmbiz.qpic.cn/sz_mmbiz_png/HYpq6iceJNftpp5MmLAyqT5xB5J53LhQaKlaDweujWs4dH3IbSmmCqSrOmX87IpVsx76jcFUsC7r624FS4HDia9w/640?wx_fmt=png"></p><p><br></p><section><span>在这场有万能青年旅店、崔健、刘宪华等艺人助阵的音乐节里，16800元可以体验到啥？</span></section><p><span><br></span></p><p><span>根据官方的介绍材料，16800元属于SVIP三天两夜露营通票，在包括音乐节权益的基础上，还包括了高档帐篷住宿和豪华配餐。不过，活动方没有注明这类票仅限单人还是多人。</span><p></p></p><p><span><br></span></p><p><img data-backh="390" data-backw="578" data-galleryid="" data-ratio="0.6753554502369669" data-s="300,640" data-src="https://mmbiz.qpic.cn/sz_mmbiz_png/HYpq6iceJNftpp5MmLAyqT5xB5J53LhQabTGQzUIDHleFKeO7Old3icBNbEyXXImexCPsNCjsA0JLVYicQEYeq7LA/640?wx_fmt=png" data-type="png" data-w="844" src="https://mmbiz.qpic.cn/sz_mmbiz_png/HYpq6iceJNftpp5MmLAyqT5xB5J53LhQabTGQzUIDHleFKeO7Old3icBNbEyXXImexCPsNCjsA0JLVYicQEYeq7LA/640?wx_fmt=png"></p><p><span line-inline="dxGN" ql-global="true">图 | 大麦网“2023 虾米xMTA天漠音乐节”1600元SVIP三天两夜露营通票参考图</span><p></p></p><p><span line-inline="dxGN" ql-global="true"><br></span></p><p><span>除了这类特殊的音乐节形式，在单场大型演唱会上，于文文、乐华家族、张艺兴等艺人（团体）演出的最低入手价格在500元左右，而最高票档，超过2500元。对比下来，周杰伦巡演的500元至2000元的价格区间，已显得平易近人。</span><p></p></p><p><span><br></span></p><p><span>当然，纵观各项演唱会形式，价格100-200元的演出价格才是多数。它们通常为一些独立音乐人和成长期艺人举办的Livehouse演出，容纳观众在数百人以内。Livehouse提供场地，从中收取低廉租金，并赚取观众的酒水消费。</span><p></p></p><p><span><br></span></p><p><img data-backh="923" data-backw="578" data-galleryid="" data-ratio="1.5972222222222223" data-s="300,640" data-src="https://mmbiz.qpic.cn/sz_mmbiz_png/HYpq6iceJNftpp5MmLAyqT5xB5J53LhQarLNjUMspgGqzwJeQbP9dPicDGym1VzmY1Aq1iaNicphDqOcFkm0bPpJzw/640?wx_fmt=png" data-type="png" data-w="1080" src="https://mmbiz.qpic.cn/sz_mmbiz_png/HYpq6iceJNftpp5MmLAyqT5xB5J53LhQarLNjUMspgGqzwJeQbP9dPicDGym1VzmY1Aq1iaNicphDqOcFkm0bPpJzw/640?wx_fmt=png"><span></span></p><p><span> </span></p><p><span>百来元的演出价格，虽然符合大家的预期，但艺人名气有限，而难以掀起波澜。更多人感兴趣的，是五月天、周杰伦等超级明星的巡演计划，因此，相关场次的抢票就变成了“修罗场”——价格不是问题，问题是想买也买不到。</span><p></p></p><p><span><br></span></p><p><span>抢票大军中，黄牛作祟。而他们，也恰恰是让演唱会如此难抢的原因之一。翻开闲鱼，针对热门演出场次，黄牛开价会比票面价高出数倍。可即便如此，询价的也不在少数，可见人们求演唱会之心切。</span><p></p></p><p><span><br></span></p><p><span>抵制不买？黄牛不怕。6月底的周杰伦演唱会海口站，内场前十排价格一度飙到万元。歌迷望而却步，黄牛却捂着高价不肯松口。演唱会开场后，票价迅速跳水，还传出了黄牛将门票烧掉也不肯降价的视频。</span><p></p></p><p><span><br></span></p><p><span>因此，当被问到演出市场最需要改进的地方，超七成受访者表示应当打击黄牛。同时，还有不少网友呼吁实施“强实名制”，即让人脸识别、身份证与门票绑定，来遏制黄牛囤票的问题。</span><p></p></p><p><span><br></span></p><p><img data-backh="910" data-backw="578" data-galleryid="" data-ratio="1.5740740740740742" data-s="300,640" data-src="https://mmbiz.qpic.cn/sz_mmbiz_png/HYpq6iceJNftpp5MmLAyqT5xB5J53LhQaJYUgaica2jDpl98qlicBsCPXEqN7gGtXUrAro0SbsbZ2Wda2M76qBnPA/640?wx_fmt=png" data-type="png" data-w="1080" src="https://mmbiz.qpic.cn/sz_mmbiz_png/HYpq6iceJNftpp5MmLAyqT5xB5J53LhQaJYUgaica2jDpl98qlicBsCPXEqN7gGtXUrAro0SbsbZ2Wda2M76qBnPA/640?wx_fmt=png"></p><p><br></p><p><span>此前，大部分演唱会实行的是无实名制购票，或准实名制购票。后者在购票时用身份证来限购，且不支持退票。但这带来的问题是，临时有事的观众，的确有转让需求，如果完全不允许退票，又侵犯了消费者权益。</span><p></p></p><p><span><br></span></p><p><span>“转赠”机制是此前通行的做法，即在开场前允许换绑观众信息，这又给黄牛囤票，带来了可乘之机。</span><p></p></p><p><span><br></span></p><p><span>天下苦黄牛久矣。如果买到的是真票，已经能庆幸了。随着市场火热，高价卖“假票”的人也混迹其中。</span><span>演出虽多，但一座难求。</span><span>有钱还不够，还要斗智斗勇。</span></p><p><br></p><section><br></section><section><h4><section><section data-tools="135编辑器" data-id="93821"><section><section><section><span>03</span></section></section></section></section><section><br></section></section></h4><h4><strong><span><strong><span>全球演唱会价格，今年都在涨</span></strong></span></strong></h4></section><p><span>黄牛作祟、“内娱高贵”，抛开这些限定因素，演唱会的价格上扬，其实不限于国内。今年以来，全球粉丝都发现，演出价格相比疫情前上涨不少。</span><p></p></p><p><span><br></span></p><p><span>根据Pullstar的统计，上半年全球百大巡演的平均票价首次突破100美元，达到116.41美元（约835元人民币），比2022年的数据高出10.3%，比2019年的92.4美元高出26%。这一涨幅，显然高出了全球通货膨胀的速度。</span><p></p></p><p><span><br></span></p><p><span>同时，演出收入同比去年提高51.1%，售票量同比去年提高37%。生意火热。</span><p></p></p><p><span><br></span></p><p><span>在这里，百大巡演包括了中国观众熟知的碧昂丝、麦当娜、BlackPink、泰勒·斯威夫特等顶级艺人（团体）。</span><p></p></p><p><span><br></span></p><p><span>不过，作为被平均的对象，她们的巡演票价其实远不止116美元。根据SeatGeek的数据，碧昂丝和泰勒·斯威夫特巡演的实际均价分别达到了480美元和1311美元。BlackPink巡演均价为350美元。</span><p></p></p><p><span><br></span></p><p><img data-backh="886" data-backw="578" data-galleryid="" data-ratio="1.5324074074074074" data-s="300,640" data-src="https://mmbiz.qpic.cn/sz_mmbiz_png/HYpq6iceJNftpp5MmLAyqT5xB5J53LhQafnicFYmSVKIqR9A5AALg8KNOX2MfAIaXiamaXsHkTtQf5kJPuyZ1z8hg/640?wx_fmt=png" data-type="png" data-w="1080" src="https://mmbiz.qpic.cn/sz_mmbiz_png/HYpq6iceJNftpp5MmLAyqT5xB5J53LhQafnicFYmSVKIqR9A5AALg8KNOX2MfAIaXiamaXsHkTtQf5kJPuyZ1z8hg/640?wx_fmt=png"></p><p><br></p><p><span>对于中国粉丝而言，想一睹她们的风采，难度更大。除了要跟全球粉丝竞争购票，还要花上国际旅行的费用，算下来，一趟演唱会之旅，成本基本上万。</span><p></p></p><p><span><br></span></p><p><span>如此花费，值得吗？在数不清的演唱会动态、攻略、笔记里，人们乐在其中。预算不够，那就在其他地方省点。在日常饮食、出行中积攒的钱与辛苦，都要在场馆的歌声里集中释放。</span><p></p></p><p><span><br></span></p><p><span>在社交媒体上，“演唱会忧郁症”是一个热门问题，讲的是巨大期待、喜悦后带来的失落感。可即便预知到了结束后的失落，人们也愿奔赴，去看自己喜欢已久的歌星。</span><p></p></p><p><span><br></span></p><p><span>毕竟，成年人的世界里，烦恼很多。花钱就能买到的纯粹快乐，值得。<span><img data-ratio="0.9975124378109452" data-type="png" data-w="804" height="17" width="18" data-src="https://mmbiz.qpic.cn/mmbiz_png/YulpgP4g2QLtwd7aY4PhcYIYapVuObiaCxHmiaxl55EchrPoBSlVLsTwnxsJJIok1nRIibXHSmu8ibKC8plzSUOkIg/640?wx_fmt=png&amp;wxfrom=5&amp;wx_lazy=1&amp;wx_co=1" src="https://mmbiz.qpic.cn/mmbiz_png/YulpgP4g2QLtwd7aY4PhcYIYapVuObiaCxHmiaxl55EchrPoBSlVLsTwnxsJJIok1nRIibXHSmu8ibKC8plzSUOkIg/640?wx_fmt=png&amp;wxfrom=5&amp;wx_lazy=1&amp;wx_co=1"></span><span>（来源：腾讯新闻）</span></span><p></p></p><p><br></p><p><span><span><span msthash="608244" msttexthash="882882"><span><span data-raw-text="◦" data-textnode-index-1661042941272="99" data-index-1661042941272="6421">◦</span><span data-raw-text=" " data-textnode-index-1661042941272="99" data-index-1661042941272="6422"> </span></span></span></span><span>文中受访者为化名。</span></span></p><section><section powered-by="xiumi.us"><section><section><section powered-by="xiumi.us"><section><p>参考资料：</p><p>[1]证券时报，各地演唱会密集“开唱” 多维度带动相关产业发展</p><p>http://www.zqrb.cn/finance/hangyedongtai/2023-05-26/A1685029089174.html</p><p>[2]The Wall Street Journal，The Year of the $1,000 Concert Ticket</p><p>https://www.wsj.com/articles/concert-tickets-prices-expensive-cafb8dd1</p><p>[3]SeatGeek，BLACKPINK</p><p>https://seatgeek.com/blackpink-tickets</p><p>[4]央视新闻，你买不到的演出票，为什么总在“黄牛”手里？</p><p>https://mp.weixin.qq.com/s/AkJO7raJc6vTIgK_jwgwLg</p><p>[5]中国演出行业协会，2023上半年全国演出市场简报</p><p>https://mp.weixin.qq.com/s/RSLrgFiRtPtKi4SwaCaCjg</p><p>[6]Pollstar，2023 Mid-Year Business Analysis: Boxoffice Tallies Point To Banner Year</p><p>https://news.pollstar.com/2023/06/26/2023-mid-year-business-analysis-strength-in-numbers-mid-year-boxoffice-tallies-point-to-banner-year/</p></section></section></section></section></section></section><section><br></section><section><span data-darkmode-bgcolor-16366260358756="rgb(25, 25, 25)" data-darkmode-original-bgcolor-16366260358756="#fff|rgb(255, 255, 255)" data-darkmode-color-16366260358756="rgb(136, 136, 136)" data-darkmode-original-color-16366260358756="#fff|rgb(136, 136, 136)">作者｜鹿鸣</span></section><section><span data-darkmode-bgcolor-16366260358756="rgb(25, 25, 25)" data-darkmode-original-bgcolor-16366260358756="#fff|rgb(255, 255, 255)" data-darkmode-color-16366260358756="rgb(136, 136, 136)" data-darkmode-original-color-16366260358756="#fff|rgb(136, 136, 136)">设计｜<span>鹿</span><span>鸣</span></span></section><section><span>编辑 | 赤耳</span></section><section><span>出品 | 腾讯新闻 谷雨工作室</span></section><section><span>腾讯新闻出品内容，未经授权，不得复制和转载，否则将追究法律责任。</span></section><section><span><br></span></section><section><span>阅读更多请点击：</span></section><section><a target="_blank" href="http://mp.weixin.qq.com/s?__biz=MzU0Nzg4MTQ4MQ==&amp;mid=2247513947&amp;idx=1&amp;sn=fa112c20699cd926ee4a9e26a1144769&amp;chksm=fb45603dcc32e92bdb270bcdb6dfa86488a65a5d30b3d458821655f8a4b32a5faff794885323&amp;scene=21#wechat_redirect" textvalue="提前退休" linktype="text" imgurl="" imgdata="null" data-itemshowtype="0" tab="innerlink" data-linktype="2" hasload="1"><span>提前退休</span></a><span> | <a target="_blank" href="http://mp.weixin.qq.com/s?__biz=MzU0Nzg4MTQ4MQ==&amp;mid=2247513973&amp;idx=1&amp;sn=2a0cdbe47a56bc17911ae1c9d863bd2c&amp;chksm=fb456013cc32e90502d7ddaf956f2250629915f4eaf00923d00d327985aacc5458f8a8e4a27d&amp;scene=21#wechat_redirect" textvalue="假装上班" linktype="text" imgurl="" imgdata="null" data-itemshowtype="0" tab="innerlink" data-linktype="2" hasload="1">假装上班</a></span><span>丨<a target="_blank" href="http://mp.weixin.qq.com/s?__biz=MzU0Nzg4MTQ4MQ==&amp;mid=2247513868&amp;idx=1&amp;sn=6226b129fd5a03553bebced1d3502fde&amp;chksm=fb45606acc32e97c2c639ded2fcc3645dea9e2fe8d133a20601503fb6cccbeaa19e117f4d096&amp;scene=21#wechat_redirect" textvalue="电子榨菜" linktype="text" imgurl="" imgdata="null" data-itemshowtype="0" tab="innerlink" data-linktype="2" hasload="1">电子榨菜</a>丨<a href="https://mp.weixin.qq.com/s?__biz=MzU0Nzg4MTQ4MQ==&amp;mid=2247512793&amp;idx=1&amp;sn=c7a3c748b149f42e5ae7bcbd652225ad&amp;scene=21#wechat_redirect" textvalue="学医为了救人，但谁来救救医学生 | 腾讯新闻谷雨数据" target="_blank" localeditorid="73xwbguvi8ixeum2k1s" data-linktype="2">医学生</a></span></section><section><span><a target="_blank" href="http://mp.weixin.qq.com/s?__biz=MzU0Nzg4MTQ4MQ==&amp;mid=2247509084&amp;idx=1&amp;sn=a14f5130d8be1a435eaed4cdcb4c86ef&amp;chksm=fb45733acc32fa2cdeb4be63895ae08f0f86955950ad5aee9dc4f9d0ecc54347256ce07f2020&amp;scene=21#wechat_redirect" textvalue="家里蹲" linktype="text" imgurl="" imgdata="null" data-itemshowtype="0" tab="innerlink" data-linktype="2" hasload="1">家里蹲</a>丨<a target="_blank" href="http://mp.weixin.qq.com/s?__biz=MzU0Nzg4MTQ4MQ==&amp;mid=2247513367&amp;idx=1&amp;sn=4cf00e43b5d3ee2e2f8e2e50644f083a&amp;chksm=fb456271cc32eb6786b693c557d6be6f5e894218bbc228e2ffc3c2262c0dcdb5bcd16cdb8b34&amp;scene=21#wechat_redirect" textvalue="绝经" linktype="text" imgurl="" imgdata="null" data-itemshowtype="0" tab="innerlink" data-linktype="2" hasload="1">绝经</a>丨<a target="_blank" href="http://mp.weixin.qq.com/s?__biz=MzU0Nzg4MTQ4MQ==&amp;mid=2247513895&amp;idx=1&amp;sn=ce445cc8d0b49ed7ac223b83e52a2a60&amp;chksm=fb456041cc32e95760d6f5c6954d4938378f4e43e606116feedea9a2bd17e203cef7b78e47cf&amp;scene=21#wechat_redirect" textvalue="体力活" linktype="text" imgurl="" imgdata="null" data-itemshowtype="0" tab="innerlink" data-linktype="2" hasload="1">体力活</a>丨<a target="_blank" href="http://mp.weixin.qq.com/s?__biz=MzU0Nzg4MTQ4MQ==&amp;mid=2247513880&amp;idx=1&amp;sn=d4ee5aa9c2111af600207df8761ddf25&amp;chksm=fb45607ecc32e96805f472afecce60f17680c746759c0fbdbd08c69c51185cd4ef6cce5faa23&amp;scene=21#wechat_redirect" textvalue="硕博毕业人数" linktype="text" imgurl="" imgdata="null" data-itemshowtype="0" tab="innerlink" data-linktype="2" hasload="1">硕博毕业人数</a></span></section><section><a target="_blank" href="http://mp.weixin.qq.com/s?__biz=MzU0Nzg4MTQ4MQ==&amp;mid=2247513421&amp;idx=1&amp;sn=91d2f8887031ebf436cf10dd63d89851&amp;chksm=fb45622bcc32eb3df7201bd1ff898eafbc9d85a38fdce8523f2290ffffe679b37e33353d70fb&amp;scene=21#wechat_redirect" textvalue="ChatGPT" linktype="text" imgurl="" imgdata="null" data-itemshowtype="0" tab="innerlink" data-linktype="2" hasload="1"><span>ChatGPT</span></a><span>丨<a target="_blank" href="http://mp.weixin.qq.com/s?__biz=MzU0Nzg4MTQ4MQ==&amp;mid=2247513935&amp;idx=1&amp;sn=1fda38100564716a212f04a6632fbc7f&amp;chksm=fb456029cc32e93f8968ae9cd5158fc2cd9cb07a0a13f5a69e7feabf4255814920aa19f35332&amp;scene=21#wechat_redirect" textvalue="韩国婚育" linktype="text" imgurl="" imgdata="null" data-itemshowtype="0" tab="innerlink" data-linktype="2" hasload="1">韩国婚育</a>丨<a target="_blank" href="http://mp.weixin.qq.com/s?__biz=MzU0Nzg4MTQ4MQ==&amp;mid=2247513825&amp;idx=1&amp;sn=cdafea01735cfeb968989d447411afe0&amp;chksm=fb456187cc32e891d7ce10f15c4825dec5788755dc29d1d068750ad4981ac51153e6d9c8330f&amp;scene=21#wechat_redirect" textvalue="日本老年就业" linktype="text" imgurl="" imgdata="null" data-itemshowtype="0" tab="innerlink" data-linktype="2" hasload="1">日本老年就业</a></span></section><section><span>公众号对话框回复其他关键词，可查看更多文章</span></section><section><span><br></span></section><p><span><span><strong><span>最热话题+最新数据</span></strong>，值得你<span>第一时间获取</span>，大家记得将</span><span><strong><span>谷雨数据</span></strong></span><span>设为星标🌟哦，期待每次与你火速相遇！</span></span></p><p><img data-backh="366" data-backw="562" data-galleryid="" data-ratio="0.6518518518518519" data-s="300,640" data-src="https://mmbiz.qpic.cn/mmbiz_png/HYpq6iceJNftv6xOL6CpicDUMj02PBRvSyzrElgn8SB3iauQqE6j3JvfheI9tIicLqDd1EtHwHU9447MOmYUD2XZJw/640?wx_fmt=png&amp;wxfrom=5&amp;wx_lazy=1&amp;wx_co=1" data-type="png" data-w="1080" src="https://mmbiz.qpic.cn/mmbiz_png/HYpq6iceJNftv6xOL6CpicDUMj02PBRvSyzrElgn8SB3iauQqE6j3JvfheI9tIicLqDd1EtHwHU9447MOmYUD2XZJw/640?wx_fmt=png&amp;wxfrom=5&amp;wx_lazy=1&amp;wx_co=1"></p><section><span><a target="_blank" href="http://mp.weixin.qq.com/s?__biz=MzU0Nzg4MTQ4MQ==&amp;mid=2247499167&amp;idx=2&amp;sn=037326c05c353e20e26a8ffa05fcff17&amp;chksm=fb452af9cc32a3efd05edd8f2d253b6c4a21ba50dd20127f1634de16341260bc29b28943dd26&amp;scene=21#wechat_redirect" data-itemshowtype="0" tab="innerlink" data-linktype="2" wah-hotarea="click" hasload="1"><span>想和谷雨数据一起搞事，总共分几步</span></a></span></section><section><mp-common-profile data-id="MzU0Nzg4MTQ4MQ==" data-pluginname="mpprofile" data-headimg="http://mmbiz.qpic.cn/mmbiz_png/HYpq6iceJNfv6AMAciaSUe8vJHw7GgTTWgSqja83BS1GfKXXZqYhvIbfiaXxEmwjib8Jjs2F0WnsicZo2VtvYCBxmaA/0?wx_fmt=png" data-nickname="谷雨数据-腾讯新闻" data-alias="guyudata" data-signature="腾讯新闻出品、谷雨工作室旗下栏目，聚焦数据新闻、数据报告。" data-from="2" data-index="0" data-origin_num="351" data-isban="0" data-weuitheme="light" data-biz_account_status="0" data-weui-theme="light" data-is_biz_ban="0"></mp-common-profile></section><p><img data-backh="14" data-backw="578" data-cropselx1="0" data-cropselx2="562" data-cropsely1="0" data-cropsely2="14" data-ratio="0.024074074074074074" data-s="300,640" data-src="https://mmbiz.qpic.cn/mmbiz_png/HYpq6iceJNfsQnXZh1swV0TiaKxh16n43C43xV2MyUTibQxQS8CmY3xAzyp4sBziaSMyXyzyFPLPmDz9rQOLGiaWLLA/640?wx_fmt=png&amp;wxfrom=5&amp;wx_lazy=1&amp;wx_co=1" data-type="png" data-w="1080" src="https://mmbiz.qpic.cn/mmbiz_png/HYpq6iceJNfsQnXZh1swV0TiaKxh16n43C43xV2MyUTibQxQS8CmY3xAzyp4sBziaSMyXyzyFPLPmDz9rQOLGiaWLLA/640?wx_fmt=png&amp;wxfrom=5&amp;wx_lazy=1&amp;wx_co=1"></p><section><br></section><section><img data-backh="71" data-backw="562" data-ratio="0.12698412698412698" data-s="300,640" data-src="https://mmbiz.qpic.cn/mmbiz_png/HYpq6iceJNfvFy0QA9x7LoZEZCEQYR3MaMnibtwFFuDBjbna1aribibHwqF2NDfJhY1JQCa6CicPlGXu88nUmLpG2qQ/640?wx_fmt=png&amp;wxfrom=5&amp;wx_lazy=1&amp;wx_co=1" data-type="png" data-w="945" src="https://mmbiz.qpic.cn/mmbiz_png/HYpq6iceJNfvFy0QA9x7LoZEZCEQYR3MaMnibtwFFuDBjbna1aribibHwqF2NDfJhY1JQCa6CicPlGXu88nUmLpG2qQ/640?wx_fmt=png&amp;wxfrom=5&amp;wx_lazy=1&amp;wx_co=1"></section><p><mp-style-type data-value="3"></mp-style-type></p></div>

**Comment by wwlwwl2000** [comment]
这边大麦脚本可长期提供，有需要的来➕q2091248098，标明github
