### ISSUE TITLE
Shi博士教你如何合理利用学术不端实现科研事业平步青云

### ISSUE THREAD

**Issue by ixxmu** [ixxmu/hugo_duty#548]
https://mp.weixin.qq.com/s/UsPHY7ond1gT9rAoMarfSA

**Comment by ixxmu** [comment]
Shi博士教你如何合理利用学术不端实现科研事业平步青云 by 危生物组
------
<div><section><section><h1><span>Shi博士教你如何合理通过学术不端实现科研事业的弯道超车</span></h1><blockquote><p>写在前面的<br>最近看见一篇刷新我学术三观的科研弯道超车指南。当大量老老实实的科研民工为了解决眼前的科学问题而勤勤恳恳、任劳任怨地重复着科学实验工作时，有人已经通过寻找并抓住学术不端规则的漏洞实现了合理的一稿多投、抄袭他人学术成果，从而在科研论文发表的道路上平步青云，进而利用这些通过不正当学术手段得到的成果事先科研工作和事业的双丰收。并且发表这份学术不端指南的Shi博士还秉持无私分享的精神将自己的学术超车秘籍公开分享。看完这个所谓的秘籍，我实属惊叹！感慨在国家严查学术不端的当下，居然还能顶风而上，逆流而行。</p></blockquote><h3><span>Shi博士的科研弯道超车秘籍</span></h3><p><img data-galleryid="" data-imgfileid="100001554" data-ratio="0.8691695108077361" data-s="300,640" data-src="https://mmbiz.qpic.cn/sz_mmbiz_png/V6qOSNufyVSRSeaRkKhPExIDpIibmYahCCkpm3GzXqoia6ghbL8nEktV5SNnc7YHFdEtN6icThIUY6FKUhnn326WQ/640?wx_fmt=png&amp;from=appmsg" data-type="png" data-w="879" src="https://mmbiz.qpic.cn/sz_mmbiz_png/V6qOSNufyVSRSeaRkKhPExIDpIibmYahCCkpm3GzXqoia6ghbL8nEktV5SNnc7YHFdEtN6icThIUY6FKUhnn326WQ/640?wx_fmt=png&amp;from=appmsg"></p><p><img data-galleryid="" data-imgfileid="100001555" data-ratio="0.68" data-s="300,640" data-src="https://mmbiz.qpic.cn/sz_mmbiz_png/V6qOSNufyVSRSeaRkKhPExIDpIibmYahCuyia9CWTibOyIzV0licGpHNkBmnsib8FwHFibwFnUocZroI6saTbibZSGCrw/640?wx_fmt=png&amp;from=appmsg" data-type="png" data-w="875" src="https://mmbiz.qpic.cn/sz_mmbiz_png/V6qOSNufyVSRSeaRkKhPExIDpIibmYahCuyia9CWTibOyIzV0licGpHNkBmnsib8FwHFibwFnUocZroI6saTbibZSGCrw/640?wx_fmt=png&amp;from=appmsg"></p><p><img data-galleryid="" data-imgfileid="100001557" data-ratio="0.7589388696655133" data-s="300,640" data-src="https://mmbiz.qpic.cn/sz_mmbiz_png/V6qOSNufyVSRSeaRkKhPExIDpIibmYahC7cHBAfI35Z5oMx7PQSGBTgjJ311El0rVcOp6rvViadQ3cYKXjnWiciaicw/640?wx_fmt=png&amp;from=appmsg" data-type="png" data-w="867" src="https://mmbiz.qpic.cn/sz_mmbiz_png/V6qOSNufyVSRSeaRkKhPExIDpIibmYahC7cHBAfI35Z5oMx7PQSGBTgjJ311El0rVcOp6rvViadQ3cYKXjnWiciaicw/640?wx_fmt=png&amp;from=appmsg"></p><p><img data-galleryid="" data-imgfileid="100001558" data-ratio="0.8154205607476636" data-s="300,640" data-src="https://mmbiz.qpic.cn/sz_mmbiz_png/V6qOSNufyVSRSeaRkKhPExIDpIibmYahCMx4wLRvmwMnTgJxCS4EuviblLDDoPE1PUuibrydt9y81cw47LYnFL6Mg/640?wx_fmt=png&amp;from=appmsg" data-type="png" data-w="856" src="https://mmbiz.qpic.cn/sz_mmbiz_png/V6qOSNufyVSRSeaRkKhPExIDpIibmYahCMx4wLRvmwMnTgJxCS4EuviblLDDoPE1PUuibrydt9y81cw47LYnFL6Mg/640?wx_fmt=png&amp;from=appmsg"></p><p><img data-galleryid="" data-imgfileid="100001560" data-ratio="0.9431171786120591" data-s="300,640" data-src="https://mmbiz.qpic.cn/sz_mmbiz_png/V6qOSNufyVSRSeaRkKhPExIDpIibmYahCQNwYNWMsUQzxsmK37NVR6etjFChE7h12wBsrk7mxWMgUtUWBSDjlaQ/640?wx_fmt=png&amp;from=appmsg" data-type="png" data-w="879" src="https://mmbiz.qpic.cn/sz_mmbiz_png/V6qOSNufyVSRSeaRkKhPExIDpIibmYahCQNwYNWMsUQzxsmK37NVR6etjFChE7h12wBsrk7mxWMgUtUWBSDjlaQ/640?wx_fmt=png&amp;from=appmsg"></p><p><img data-galleryid="" data-imgfileid="100001561" data-ratio="0.9682179341657208" data-s="300,640" data-src="https://mmbiz.qpic.cn/sz_mmbiz_png/V6qOSNufyVSRSeaRkKhPExIDpIibmYahCKrQMj8xI2LD3U6qVUMHmZTehEOzYicIGSibWAiaMxgNavmVibSGCOicBrWA/640?wx_fmt=png&amp;from=appmsg" data-type="png" data-w="881" src="https://mmbiz.qpic.cn/sz_mmbiz_png/V6qOSNufyVSRSeaRkKhPExIDpIibmYahCKrQMj8xI2LD3U6qVUMHmZTehEOzYicIGSibWAiaMxgNavmVibSGCOicBrWA/640?wx_fmt=png&amp;from=appmsg"></p><p><img data-galleryid="" data-imgfileid="100001562" data-ratio="0.8591385331781141" data-s="300,640" data-src="https://mmbiz.qpic.cn/sz_mmbiz_png/V6qOSNufyVSRSeaRkKhPExIDpIibmYahC6anJeMYaDvmz4d7d2lDfYLXB3oq3rl2YcK9SM415OQCEOic9IVodpEA/640?wx_fmt=png&amp;from=appmsg" data-type="png" data-w="859" src="https://mmbiz.qpic.cn/sz_mmbiz_png/V6qOSNufyVSRSeaRkKhPExIDpIibmYahC6anJeMYaDvmz4d7d2lDfYLXB3oq3rl2YcK9SM415OQCEOic9IVodpEA/640?wx_fmt=png&amp;from=appmsg"></p><h3><span>Shi博士何许人也</span></h3><p>Shi博士自称施b辰，是清华大学"水木学者"、国家级人才计划青年拔尖人才(29岁获得,中国历史上最年轻)。他在清华大学电机工程与应用电子技术系获得学士和博士学位,主要从事电力电子混杂系统动力学表征、多尺度建模仿真及其工业软件的研究工作。施b辰主持和参与了多项国家级科研项目,包括国家重点研发计划、国家自然科学基金等。他发表了40余篇SCI/EI论文,获得了10余项中国发明专利和2项美国发明专利。施b辰在学术界取得了非常出色的成绩,获得了多项国内外重要奖项,包括教育部科技进步一等奖、日内瓦国际发明展评审团特别金奖、IEEE PELS P3 Talk Award等。据介绍,施b辰目前担任迪盛迅达(北京)科技有限公司的CTO(首席技术官),主要负责该公司首款自主化和世界首套基于状态离散的电力电子工业仿真软件DSIM的开发。这款软件被誉为"电力电子行业的AutoCAD",可以帮助企业大幅提高电力电子系统设计和仿真的效率。综上所述,施b辰不仅在学术研究方面取得了卓越成就,还在工业界担任重要职务,负责公司的核心技术研发工作。可以说,他在学术和工业领域都有出色的表现。(清华大学预防与处理学术不端行为办法-清华大学 (tsinghua.edu.cn))</p><h3><span>清华大学预防与处理学术不端行为办法</span></h3><p>清华大学有明确的《预防与处理学术不端行为办法》,规定学校将坚持"预防为主、教育与惩戒相结合"的原则来处理学术不端行为。根据该办法,Shi博士的行为可能会受到调查和处理。但是Shi博士的弯道超车秘籍中堂而皇之提到了他的学术不端行为并不满足清华大学预防与处理学术不端行为办法中列举的条件，所以他的行为完全合规不会有任何被处理的风险。</p><p><img data-galleryid="" data-imgfileid="100001565" data-ratio="0.9018538713195202" data-s="300,640" data-src="https://mmbiz.qpic.cn/sz_mmbiz_png/V6qOSNufyVSRSeaRkKhPExIDpIibmYahCibOuW4tK92wcgTpnAia8jnGVP87tia1zCpWfL7O95VlFnzFic3Ke4qf2XQ/640?wx_fmt=png&amp;from=appmsg" data-type="png" data-w="917" src="https://mmbiz.qpic.cn/sz_mmbiz_png/V6qOSNufyVSRSeaRkKhPExIDpIibmYahCibOuW4tK92wcgTpnAia8jnGVP87tia1zCpWfL7O95VlFnzFic3Ke4qf2XQ/640?wx_fmt=png&amp;from=appmsg"></p><p><img data-galleryid="" data-imgfileid="100001566" data-ratio="0.8633333333333333" data-s="300,640" data-src="https://mmbiz.qpic.cn/sz_mmbiz_png/V6qOSNufyVSRSeaRkKhPExIDpIibmYahCsQvKLC6vQkB4T13S9SlEtSY7MgY4tTaYVPDdkydx1TV7YoibbapOrfw/640?wx_fmt=png&amp;from=appmsg" data-type="png" data-w="900" src="https://mmbiz.qpic.cn/sz_mmbiz_png/V6qOSNufyVSRSeaRkKhPExIDpIibmYahCsQvKLC6vQkB4T13S9SlEtSY7MgY4tTaYVPDdkydx1TV7YoibbapOrfw/640?wx_fmt=png&amp;from=appmsg"></p><p><img data-galleryid="" data-imgfileid="100001567" data-ratio="0.7282976324689966" data-s="300,640" data-src="https://mmbiz.qpic.cn/sz_mmbiz_png/V6qOSNufyVSRSeaRkKhPExIDpIibmYahCwraRsucLUTBW6sKxhpxCTTVhdgLOnCicjFcibXHbDq7GIQuJbM4icpajA/640?wx_fmt=png&amp;from=appmsg" data-type="png" data-w="887" src="https://mmbiz.qpic.cn/sz_mmbiz_png/V6qOSNufyVSRSeaRkKhPExIDpIibmYahCwraRsucLUTBW6sKxhpxCTTVhdgLOnCicjFcibXHbDq7GIQuJbM4icpajA/640?wx_fmt=png&amp;from=appmsg"></p><h3><span>学术不端背后的些许原因</span></h3><h4><span>升迁和获取研究资源的压力</span></h4><p>中国大陆的大学普遍以发表论文数量作为教职员工升迁和获取研究资金的重要标准。这种机制鼓励教职员工不惜手段地大量发表论文,导致了严重的学术造假问题。</p><h4><span>论文工厂的泛滥</span></h4><p>近年来,随着人工智能技术的发展,一些非法的"论文工厂"应运而生。这些工厂专门为需要发表论文的人员提供代写、代发论文的服务,造假行为猖獗。中国已成为这些论文工厂的重灾区。</p><h4><span>医疗界的特殊压力</span></h4><p>在医疗领域,发表论文数量更是医生职称晋升和申请科研经费的重要指标，狭隘地说，在某些程度上，评价一个医生是否优秀的标准不是这名医生完成了多少台手术救治了多少病人，而是看这个医生发表了多少论文，拿到了多少科研经费。这种机制迫使一些医生不得不通过各种手段来完成论文发表任务,导致了医疗界尤其严重的造假问题。</p><h4><span>缺乏有效监管</span></h4><p>目前,对学术造假行为的监管和惩处机制还不够完善,很多造假行为得以逃脱。这也给了一些不法分子可乘之机,助长了学术造假的猖獗。总体而言,中国科研造假的根源在于过于简单化的评价机制,以及监管不力。只有通过深化职称制度改革,建立健全的学术诚信体系,才能从根本上遏制这一问题。</p><h3><span>防范学术不端的些许见解</span></h3><p>1.建立健全的学术道德规范和监督机制。各高校应该制定明确的学术行为准则,并设立专门的学术道德建设委员会负责受理举报、调查处理学术不端行为。<br>2.加强对师生的学术诚信教育。通过开展学术道德培训、案例分析等方式,增强师生的学术诚信意识,引导他们自觉遵守学术规范。<br>3.完善学术评价机制。在学术评价中,应该坚持公正、客观、全面的原则,避免简单化的量化指标。同时加强对重大科研成果的论证和鉴定,防止学术不端行为的发生。<br>4.严惩学术不端行为。对于经调查确认的学术不端行为,应当依据严格的处理程序和标准,给予相应的处分,如通报批评、撤销学位、开除等。对于严重违反学术道德的,还应当通知相关资助方。营造良好的学术生态。学校和科研机构应该营造宽松、自由的学术氛围,鼓励创新、尊重知识产权,为师生提供良好的学术发展环境。</p></section></section><p>5.Shi博士在其秘籍中还提到将课题组内已毕业前辈的未发表为SCI论文的章节进行翻译发表。事实上这种行为是否学术不端需要在特定的情况下进行判断，如果已毕业前辈的毕业论文中确实存在一些未发表的课题，这些课题之所以没有发表的原因是因为当前的数据还不够完善，需要进一步的实验和研究才可能发表，在这种情况下，应该是由课题组导师事先告知已毕业学生，这部分课题将由课题组的哪一位师弟或师妹接手开展后续工作，并且最后发表论文时作者排名和排序应该是怎么样的，在取得三方了解和同意的前提下是没有任何问题的，毕竟任何一项未发表的课题在符合学术规范的情况下继续研究对于课题组而言都是有许多潜在价值的意义的。但是，如果课题组已毕业学生的未发表课题数据已经夯实了，之所以没有发表是因为已毕业学生的就业或其他原因没有及时发表，此时课题组师弟师妹在未经过导师和前辈同意的情况下直接将其翻译为英文进行发表完全是属于学术不端，抄袭剽窃他人成果。因此针对这种行为正确的做法是1.事先告知全部与该课题有关的人员，2.取得大家的知情及全部同意后才能继续研究并发表。</p><p>6.学术道德规范和基本道德素养一样是每个科研工作者必须遵守的基本准则。任何人都应该在内心保留这份戒尺，时刻严于律己。</p><p><mp-style-type data-value="3"></mp-style-type></p></div>

**Comment by tjdida** [comment]
老哥 原始连接 还有吗 怎么没了

**Comment by tjdida** [comment]
> > 老哥 原始连接 还有吗 怎么没了
> 
> 最上面不是文章原始连接么

不是吧  最开始是 github link。。。  看知乎 好像 都被删了 知乎 也没有了

**Comment by wynla** [comment]
> > > 老哥 原始连接 还有吗 怎么没了
> > 
> > 
> > 最上面不是文章原始连接么
> 
> 不是吧 最开始是 github link。。。 看知乎 好像 都被删了 知乎 也没有了

github有新的，ShiArthurX
